# Run `/function example/kit` in a test world to receive every teaching asset.
give @s utilitycraft:example_cobble_generator 1
give @s utilitycraft:example_deepslate_generator 1
give @s utilitycraft:example_thermal_crusher 1
give @s utilitycraft:example_infuser 1
give @s utilitycraft:example_fluid_washer 1
give @s utilitycraft:example_gas_reactor 1
give @s utilitycraft:example_solar_generator 1
give @s utilitycraft:example_biofuel_generator 1
give @s utilitycraft:example_gas_turbine 1
give @s utilitycraft:example_speed_upgrade 4
give @s utilitycraft:example_efficiency_upgrade 4
give @s utilitycraft:example_batch_upgrade 4
give @s utilitycraft:example_thermal_upgrade 4
give @s utilitycraft:example_coolant_capsule 8
give @s utilitycraft:example_biofuel_capsule 8
give @s utilitycraft:example_hydrogen_capsule 8
give @s utilitycraft:example_empty_fluid_capsule 8
give @s utilitycraft:example_empty_gas_capsule 8
give @s utilitycraft:example_creative_coolant_tank 1
give @s utilitycraft:example_creative_biofuel_tank 1
give @s utilitycraft:example_creative_hydrogen_tank 1
give @s utilitycraft:example_creative_exhaust_tank 1
give @s utilitycraft:example_hammer 1
give @s utilitycraft:example_mesh 1
give @s utilitycraft:example_fishing_net 1
give @s utilitycraft:example_crystal_seeds 8
give @s utilitycraft:example_casing 64
give @s utilitycraft:example_factory_crusher 1
give @s utilitycraft:example_biofuel_dynamo 1
give @s utilitycraft:example_energy_cell 8
give @s utilitycraft:example_fluid_cell 4
give @s utilitycraft:example_processing_module 4
give @s utilitycraft:example_speed_module 4
give @s utilitycraft:example_efficiency_module 4
give @s utilitycraft:example_item_port 4
give @s utilitycraft:example_fluid_port 4
give @s utilitycraft:example_energy_port 4
give @s utilitycraft:example_gas_port 4
